### ISSUE TITLE
One Plugin Question

### ISSUE THREAD

**Issue by Applepiee** [Philio/bootstrapdefault#1]
Hello sir,
You can't imagine how much I like this clean theme.
But there is one thing that's really important for me that doesn't seem to be working.
The Plugin GThumb+ (http://piwigo.org/ext/extension_view.php?eid=591)
It gives a really nice modern look to the image section on my opinion. Is there any way to make this compatible?

Thank you so much!

**Comment by Applepiee** [comment]
Also the "Header Manager" Plugin would be nice so we can replace the text on top with a banner. http://piwigo.org/ext/extension_view.php?eid=608

**Comment by Philio** [comment]
Thanks for your feedback!

I'll have to delve into how these plugins are working and see if I can make any changes to better support them.

If they are doing HTML replacements this might be the reason that they're not working as I'm aware I'm not completely following convention that is necessary for this to work. I wasn't really aware that was was common for plugins to do until someone pointed this out to me recently on the forum.

Part of the reason for releasing the theme as a preview was that I don't have much knowledge about the Piwigo platform so expected that some things (especially plugins) may have some issues.

**Comment by Applepiee** [comment]
I see.. Well Any idea how I can add an image on the top instead of text?
Thanks for your help

**Comment by Philio** [comment]
Ok, I've fixed the issue with GThumb in master, this now displays correctly and I'm detecting the prescense of the plugin to remove the extra buttons from the menu too.

![GThumb local demo](https://cloud.githubusercontent.com/assets/237850/7907756/5a1579ca-0835-11e5-8056-20eff07dd5c6.png)

**Comment by Philio** [comment]
Ok, the other one is fixed too.
I'll release a new preview build shortly.
