### ISSUE TITLE
Github version error

### ISSUE THREAD

**Issue by xbgmsharp** [Philio/bootstrapdefault#11]
Hello,

I have try the themes v1.0.0. Looks greats.
I then deleted the folder and clone the github repository.
```
# git clone git@github.com:Philio/bootstrapdefault.git
```

However some file are missing.
```
Warning: filemtime(): stat failed for ./themes/bootstrapdefault/bootstrap/dist/js/bootstrap.min.js in /var/www/piwigo/include/template.class.php on line 1894

Warning: filemtime(): stat failed for ./themes/bootstrapdefault/bootstrap/dist/css/bootstrap.min.css in /var/www/piwigo/include/template.class.php on line 1894

Warning: filemtime(): stat failed for ./themes/bootstrapdefault/bootstrap/dist/css/bootstrap-theme.min.css in /var/www/piwigo/include/template.class.php on line 1894
```

I believe it the non recursive repository, as the bootstrap directory point to bootstrap github repository.
Would be nice to update the README.md.

**Comment by xbgmsharp** [comment]
Solution 
```
# git clone --recursive git@github.com:Philio/bootstrapdefault.git
```
The bootstrap is quite big.

**Comment by Philio** [comment]
Bootstrap and Selectize.js are submodules, so if your git settings don't clone the submodules automatically you can run:

    git submodule update --init

**Comment by Philio** [comment]
Also, if you clone master there is no difference from the downloadable package, any pre-release changes are in other branches. The release script bundles only the required files (which is just the dist folders from the submodules) so the package is much smaller.
