### ISSUE TITLE
Plugin OpenStreetMap

### ISSUE THREAD

**Issue by xbgmsharp** [Philio/bootstrapdefault#13]
The plugin OpenStreetMap does not appear with the theme.
I am using the latest github version.
The OpenStreetMap plugin allow to display a map in a similar way to the Metadata details.
http://piwigo.org/ext/extension_view.php?eid=701

**Comment by xbgmsharp** [comment]
The same issue apply to Forecast plugin.
The Forecast plugin allow to display the overcast in a similar way to the Metadata details.
http://piwigo.org/ext/extension_view.php?eid=795

**Comment by Philio** [comment]
I'll look into these plugins not working, thanks for reporting.

**Comment by Philio** [comment]
Both plugins should now appear in the sidebar, however you must select an "add before" option that is actually visible in the sidebar with this theme. Options like rating and views that are displayed on the main page will not work.
