### ISSUE TITLE
Rating star display on top of infomration panel

### ISSUE THREAD

**Issue by xbgmsharp** [Philio/bootstrapdefault#14]
The star for "Average rating" and "Rate this photo" are display on top of information panel
<img width="262" alt="screen shot 2015-07-30 at 3 05 24 pm" src="https://cloud.githubusercontent.com/assets/1498985/8984952/b608985a-36cc-11e5-825d-a8341b50eefc.png">

**Comment by Philio** [comment]
Confirmed on 1.0.1.
Presumably a simple z index issue, I'll take a look later.
