### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by biouman2034** [Philio/bootstrapdefault#17]
Hello Philio,

Great idea this theme for Piwigo ! Is it possible to hide the div "Jumbotron" during browsing pictures ?
Thanks for your help

Best Regards,
Karim

**Comment by Philio** [comment]
I think it would be nice to add an option for this. It's one of by biggest annoyances with the theme myself!

**Comment by biouman2034** [comment]
Resize it by using Custom CSS is not enough. Anyway your work is great.
Can you create this option in a future release or update ?

Karim

2015-08-11 17:20 GMT+02:00 Phil Bayfield <notifications@github.com>:

**Comment by Philio** [comment]
I was thinking of changing it to work the same way as the slideshow mode does (menu and Jumbotron) not shown, via an admin option.

**Comment by biouman2034** [comment]
That's exactly what I want ! Thanks for your reply.

Karim

2015-08-11 17:26 GMT+02:00 Phil Bayfield <notifications@github.com>:

**Comment by biouman2034** [comment]
Thank you Phil for the feature.
Awesome !

Bye

Cet e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
<https://www.avast.com/fr-fr/lp-safe-emailing-2109?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=OA-2109-A>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Karim

2016-03-20 15:53 GMT+01:00 Phil Bayfield <notifications@github.com>:
