### ISSUE TITLE
Google Analytics Code

### ISSUE THREAD

**Issue by Applepiee** [Philio/bootstrapdefault#2]
Hello,
Where do I add my google analytics code? Tried adding it in the footer.tpl but that seems to be giving some odd errors.

Side note: Adding Support for PWG Stuffs (plugin made by the official pwigio team) would also be extremely kind! Would be even more awesome if you could make it a little more pretty and bootstrap like (by using small thumbs)

Thanks!

**Comment by Philio** [comment]
I actually use a plugin for this on my own site:

http://piwigo.org/ext/extension_view.php?eid=174

**Comment by Philio** [comment]
Open to suggestions on which plugins you think would be good to update, I've already done the language switch:

http://piwigo.org/ext/extension_view.php?eid=797

**Comment by Philio** [comment]
As there hasn't been any update for over a month I'm closing this, but feel free to reopen if you have further input.
