### ISSUE TITLE
Help with changing the theme

### ISSUE THREAD

**Issue by Nichlas** [Philio/bootstrapdefault#21]
Where do i change the margins of the jumbotron? 

I'd like the header part of the site to take much less space, so it will be easier to browse through photos using the arrow keys.

**Comment by Philio** [comment]
Hi, sorry for the slow reply, didn't notice your issue on here.

That's just a standard Bootstrap CSS style I think? You can add custom CSS in the admin page.

**Comment by Nichlas** [comment]
I wasn't very quick to see your reply either.

Adding custom css works brilliantly. Thank you.
