### ISSUE TITLE
Menu Bar Top Navigation Disappears in Picture

### ISSUE THREAD

**Issue by Applepiee** [Philio/bootstrapdefault#3]
When you go into a picture the top menu will disappear for some reason. Is this intentional?

**Comment by Philio** [comment]
Can you give me an example link or screenshot?

**Comment by Applepiee** [comment]
http://www.onepiecehentaidb.com/picture.php?/746/category/43

**Comment by Philio** [comment]
I'm glad I didn't open your site from work :)

How did you go about customising the theme, is it just custom CSS? Perhaps if you could provide me with your customisations I could see if I can replicate it locally.

**Comment by MCMic** [comment]
I got the same problem.
No custom CSS.

**Comment by Philio** [comment]
I wonder if it's something to do with the settings? There are no issues on my own site, e.g. https://phil.si/picture.php?/3618/category/198

**Comment by MCMic** [comment]
You’re right, nothing to do with the theme, there is an option «show menu» you need to tick in the settings of piwigo.
IMO you can close this

**Comment by Philio** [comment]
Thanks for confirming that, I'll close the issue.
