### ISSUE TITLE
Photo page icons stacked vertically

### ISSUE THREAD

**Issue by kjodle** [Philio/bootstrapdefault#33]
On the mobile view, the photo page icons (slideshow, download, etc.) stack vertically, which takes up a lot of space. Am I missing something in the theme options?

I have changed this with the following custom css:

`ul.nav.navbar-nav li {
    float: left;
}`

Any plans to change this in future versions of the theme?

Also, the `ul.nav.navbar-nav` class is used in other areas of the theme, causing issues with how they are displayed.

**Comment by Philio** [comment]
I think this is the default Bootstrap behaviour for mobile.

You'd have to refer to the Bootstrap docs in regards to changing this as I'm not sure.

**Comment by tkuther** [comment]
This is a bootstrap navbar collapse issue due to havin two navbars. The solution is to define a button for each navbar explicitly. #30 fixes this.

**Comment by Philio** [comment]
This will be fixed in the next release.
