### ISSUE TITLE
PHP errors when menu items are removed

### ISSUE THREAD

**Issue by Iva83** [Philio/bootstrapdefault#44]
I have installed the theme on a fresh install of Piwigo and I saw the option to remove some of the menu items. I removed "Related Tags" and "Specials" and the following happened:

**Warning: Attempt to modify property of non-object in /mounted-storage/home44c/sub001/sc27969-FHUU/www/v/themes/bootstrapdefault/include/themecontroller.php on line 41

Warning: Cannot modify header information - headers already sent by (output started at /mounted-storage/home44c/sub001/sc27969-FHUU/www/v/themes/bootstrapdefault/include/themecontroller.php:41) in /mounted-storage/home44c/sub001/sc27969-FHUU/www/v/include/page_header.php on line 101**

Is this on my end or is this a theme error?

**Comment by Philio** [comment]
Thanks for reporting this, I was able to replicate on my own installs.

Will look to resolve in the next release.
