### ISSUE TITLE
Returning update message for Bootstrap Default

### ISSUE THREAD

**Issue by EelcoA** [Philio/bootstrapdefault#51]
Hi,
I installed Bootstrap Darkroom and Bootstrap Default. For the default I keep getting notifications that it has to be updated. When I do that it reports successful update, but back to the admin home the message reappears. 

piwigo: 2.86
php 7
fotos.baseneelco.nl

**Comment by zoruspointorg** [comment]
have this issue too...
piwigo 2.8.6
php 5.6.3

**Comment by Philio** [comment]
The version number is wrong in the config file.

Fixed by #54
